name: Windows Static Library Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        configuration: [Release]
    
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      # 设置MSVC编译器环境
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      
      # 安装必要的依赖
      - name: Install dependencies
        run: |
          echo "No additional dependencies needed for basic build"
        shell: bash
      
      # 创建构建目录
      - name: Create build directory
        run: mkdir -p build
        shell: bash
      
      # 编译静态库 - 使用bash shell和make命令
      - name: Build static library
        shell: bash
        run: |
          # 设置构建静态库的环境变量
          export STATIC=1
          
          # 设置编译器和链接器为MSVC
          export CC=cl
          export CXX=cl
          export AR=lib
          export ARFLAGS="/NOLOGO"
          
          # 修复MSVC不兼容的问题
          export CPPFLAGS="-DCEED_SKIP_VISIBILITY -D__restrict__=__restrict"
          
          # 设置编译选项 - 使用Windows风格的路径和正确的MSVC选项
          export CFLAGS="/nologo /O2 /W3 /wd4100 /wd4127 /wd4244 /wd4267 /wd4800 /D_CRT_SECURE_NO_WARNINGS"
          export CXXFLAGS="/nologo /O2 /W3 /wd4100 /wd4127 /wd4244 /wd4267 /wd4800 /D_CRT_SECURE_NO_WARNINGS"
          
          # 注意：移除OPT变量，直接在CFLAGS中指定优化级别
          unset OPT
          
          # 执行构建 - 使用更具体的命令
          make lib -e
      
      # 验证构建结果
      - name: Verify build
        run: |
          # 查找生成的静态库文件
          Get-ChildItem -Recurse -Filter "*.lib" -Path .
          Get-ChildItem -Recurse -Filter "*.a" -Path .
        shell: powershell
      
      # 保存构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libCEED-static-lib-${{ matrix.arch }}-${{ matrix.configuration }}
          path: |
            lib/libceed.lib
            lib/libceed.a
            include/**/*.h
